apiVersion: v1
kind: Namespace
metadata:
  name: ssd-tier
---
apiVersion: v1
kind: Namespace
metadata:
  name: hdd-tier
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-storage
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
