# Secret
apiVersion: v1
kind: Secret
metadata:
  name: ssd-db-sec
  namespace: ssd-tier
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: "test123"
  MYSQL_USER: "tomuser"
  MYSQL_PASSWORD: "test123"
  MYSQL_DATABASE: "tomdb"
---
# Database Service
apiVersion: v1
kind: Service
metadata:
  name: ssd-db-svc
  namespace: ssd-tier
spec:
  selector:
    app: ssd-db
  ports:
  - port: 3306
  clusterIP: None
---
# Database StatefulSet
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ssd-db
  namespace: ssd-tier
spec:
  serviceName: ssd-db-svc
  replicas: 1
  selector:
    matchLabels:
      app: ssd-db
  template:
    metadata:
      labels:
        app: ssd-db
        tier: database
    spec:
      nodeSelector:
        disk-type: ssd
      tolerations:
      - key: storage
        operator: Equal
        value: ssd
        effect: NoSchedule
      containers:
      - name: mysql
        image: mysql:5.7
        envFrom:
        - secretRef:
            name: ssd-db-sec
        ports:
        - containerPort: 3306
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 250m
            memory: 512Mi
        readinessProbe:
          exec:
            command: ["mysqladmin", "ping", "-h", "localhost"]
          initialDelaySeconds: 30
          periodSeconds: 10
---
# Application PV
apiVersion: v1
kind: PersistentVolume
metadata:
  name: ssd-tom-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-storage
  nfs:
    path: /shared/ssd
    server: SERVER_IP
---
# Application PVC
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ssd-tom-pvc
  namespace: ssd-tier
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-storage
  resources:
    requests:
      storage: 1Gi
---
# Application ConfigMap
apiVersion: v1
kind: ConfigMap
metadata:
  name: ssd-tom-configmap
  namespace: ssd-tier
data:
  index.jsp: |
    <%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
    <%@ page import="java.sql.*"%>
    <html>
    <head><title>SSD Tier</title></head>
    <body style="font-family:Arial;padding:20px;">
    <h1 style="color:#4CAF50;">✅ SSD Tier - Fast Storage</h1>
    <%
    Connection conn=null;
    try{
        String Url="jdbc:mysql://ssd-db-svc/tomdb";
        String Id="tomuser";
        String Pass="test123";
        Class.forName("com.mysql.cj.jdbc.Driver");
        conn=DriverManager.getConnection(Url,Id,Pass);
        out.println("<p style='color:green;font-size:18px;'>✅ WAS-DB Connection Success!</p>");
        out.println("<p><b>Storage:</b> SSD (Fast)</p>");
        out.println("<p><b>CPU Limit:</b> 25%</p>");
    }catch(Exception e){
        out.println("<p style='color:red;'>❌ Failed: "+e.getMessage()+"</p>");
    }finally{
        if(conn!=null) conn.close();
    }
    %>
    </body>
    </html>
---
# Application Service
apiVersion: v1
kind: Service
metadata:
  name: ssd-tom-svc
  namespace: ssd-tier
spec:
  selector:
    app: ssd-tom
  ports:
  - port: 8080
---
# Application Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ssd-tom
  namespace: ssd-tier
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ssd-tom
  template:
    metadata:
      labels:
        app: ssd-tom
        tier: application
    spec:
      nodeSelector:
        disk-type: ssd
      tolerations:
      - key: storage
        operator: Equal
        value: ssd
        effect: NoSchedule
      containers:
      - name: tomcat
        image: 61.254.18.30:5000/tomcat
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 200m
            memory: 512Mi
        volumeMounts:
        - name: index
          mountPath: /usr/local/tomcat/webapps/ROOT/index.jsp
          subPath: index.jsp
        - name: ssd-lib-vol
          mountPath: /usr/local/tomcat/lib/mysql-connector-java-8.0.23.jar
          subPath: mysql-connector-java-8.0.23.jar
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
      volumes:
      - name: index
        configMap:
          name: ssd-tom-configmap
          items:
          - key: index.jsp
            path: index.jsp
      - name: ssd-lib-vol
        persistentVolumeClaim:
          claimName: ssd-tom-pvc 
---
# Web ConfigMap
apiVersion: v1
kind: ConfigMap
metadata:
  name: ssd-nginx-configmap
  namespace: ssd-tier
data:
  default.conf: |
    server {
      listen 80;
      location / {
          proxy_pass http://ssd-tom-svc:8080/;
          proxy_set_header Host $host;
      }
    }
---
# Web Service
apiVersion: v1
kind: Service
metadata:
  name: ssd-nginx-svc
  namespace: ssd-tier
spec:
  type: LoadBalancer
  selector:
    app: ssd-nginx
  ports:
  - port: 80
---
# Web Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ssd-nginx
  namespace: ssd-tier
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ssd-nginx
  template:
    metadata:
      labels:
        app: ssd-nginx
        tier: web
    spec:
      nodeSelector:
        disk-type: ssd
      tolerations:
      - key: storage
        operator: Equal
        value: ssd
        effect: NoSchedule
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 10m
            memory: 64Mi
          limits:
            cpu: 20m
            memory: 128Mi
        volumeMounts:
        - name: config
          mountPath: /etc/nginx/conf.d/default.conf
          subPath: default.conf
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 3
      volumes:
      - name: config
        configMap:
          name: ssd-nginx-configmap
